name: CI Non Prod

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - STAGING

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets[format('DATABRICKS_HOST_{0}', github.event.inputs.environment^^)] }}
      DATABRICKS_TOKEN:  ${{ secrets[format('DATABRICKS_TOKEN_{0}', github.event.inputs.environment^^)] }}

    steps:
      - uses: actions/checkout@v1

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"