name: CI Non Prod

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - staging

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_${GITHUB_REF_SLUG^^} }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN_${GITHUB_REF_SLUG^^} }}

    steps:
      - uses: actions/checkout@v1

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"